image: gitpod/workspace-full

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: ./gradlew build
    command: ./gradlew run
  - command: sudo docker-up
    name: Docker daemon
  - command: docker
