image: gitpod/workspace-full

ports:
  - port: 8443
  - port: 9000
  - port: 8081

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sudo docker-up
  - init: ./gradlew build
    command: ./gradlew run
  - command: cd /workspace/connect/container-support/compose && sudo ./start-stack.sh
  - command: sudo docker run -p 8081:8080 -e SWAGGER_JSON=/var/swagger/fhir.json -v $PWD/swagger:/var/swagger swaggerapi/swagger-ui